// <auto-generated />
namespace Webapp_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_genre));
        
        string IMigrationMetadata.Id
        {
            get { return "202208020529361_add_genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
